apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  labels:
    io.kompose.service: community-data
  name: community-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
