apiVersion: v1
kind: PersistentVolumeClaim
metadata:  
  labels:
    io.kompose.service: community-log
  name: community-log
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
