apiVersion: v1
kind: PersistentVolumeClaim
metadata:  
  labels:
    io.kompose.service: controlpanel-data
  name: controlpanel-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
