apiVersion: v1
kind: PersistentVolumeClaim
metadata:  
  labels:
    io.kompose.service: onlyoffice-control-panel-claim0
  name: onlyoffice-control-panel-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
