apiVersion: v1
kind: PersistentVolumeClaim
metadata:  
  labels:
    io.kompose.service: onlyoffice-mysql-server-claim1
  name: onlyoffice-mysql-server-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
