apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert --controller replicationController --replicas 2 --controller statefulset
    kompose.version: 1.26.1 (a9d05d509)

  labels:
    io.kompose.service: onlyoffice-rabbitmq
  name: onlyoffice-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: onlyoffice-rabbitmq
  serviceName: onlyoffice-rabbitmq
  template:
    metadata:      
      labels:
        io.kompose.service: onlyoffice-rabbitmq
    spec:
      containers:
        - image: rabbitmq
          name: onlyoffice-rabbitmq
          ports:
            - containerPort: 5672
          resources: {}
      restartPolicy: Always
  updateStrategy: {}
status:
  replicas: 0