apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --controller replicationController --replicas 2 --controller statefulset
    kompose.version: 1.26.1 (a9d05d509)  
  labels:
    io.kompose.service: onlyoffice-postgresql
  name: onlyoffice-postgresql
spec:
  clusterIP: None
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: onlyoffice-postgresql
  type: ClusterIP
status:
  loadBalancer: {}
