apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert --controller replicationController --replicas 2 --controller statefulset
    kompose.version: 1.26.1 (a9d05d509) 
  labels:
    io.kompose.service: onlyoffice-postgresql
  name: onlyoffice-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: onlyoffice-postgresql
  serviceName: onlyoffice-postgresql
  template:
    metadata:      
      labels:
        io.kompose.service: onlyoffice-postgresql
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: onlyoffice
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: POSTGRES_USER
              value: onlyoffice
          image: postgres:9.5
          name: onlyoffice-postgresql
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /app/onlyoffice/DocumentServer/db
              name: postgresql-data
      restartPolicy: Always
  updateStrategy: {}
  volumeClaimTemplates:
    - metadata:      
        labels:
          io.kompose.service: postgresql-data
        name: postgresql-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
      status: {}
status:
  replicas: 0
