apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --controller replicationController --replicas 2 --controller statefulset
    kompose.version: 1.26.1 (a9d05d509)  
  labels:
    io.kompose.service: onlyoffice-documentserver
  name: onlyoffice-documentserver
spec:
  type: LoadBalancer
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
  selector:
    io.kompose.service: onlyoffice-documentserver  
status:
  loadBalancer: {}