apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  labels:
    io.kompose.service: onlyoffice-documentserver-claim2
  name: onlyoffice-documentserver-claim2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
