apiVersion: v1
kind: PersistentVolumeClaim
metadata:  
  labels:
    io.kompose.service: onlyoffice-documentserver-claim4
  name: onlyoffice-documentserver-claim4
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
