apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert --controller replicationController --replicas 2 --controller statefulset
    kompose.version: 1.26.1 (a9d05d509) 
  labels:
    io.kompose.service: onlyoffice-documentserver
  name: onlyoffice-documentserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: onlyoffice-documentserver
  serviceName: onlyoffice-documentserver
  template:
    metadata:   
      labels:
        io.kompose.service: onlyoffice-documentserver
    spec:
      containers:
        - env:
            - name: AMQP_URI
              value: amqp://guest:guest@onlyoffice-rabbitmq
            - name: DB_HOST
              value: onlyoffice-postgresql
            - name: DB_NAME
              value: onlyoffice
            - name: DB_PORT
              value: "5432"
            - name: DB_TYPE
              value: postgres
            - name: DB_USER
              value: onlyoffice
          image: onlyoffice/documentserver:latest
          name: onlyoffice-documentserver          
          ports:
            - containerPort: 80
            - containerPort: 443
          resources: {}
          stdin: true
          volumeMounts:
            - mountPath: /app/onlyoffice/DocumentServer/data
              name: onlyoffice-documentserver-claim0
            - mountPath: /app/onlyoffice/DocumentServer/logs
              name: onlyoffice-documentserver-claim1
            - mountPath: /app/onlyoffice/DocumentServer/lib
              name: onlyoffice-documentserver-claim2
            - mountPath: /app/onlyoffice/DocumentServer/rabbitmq
              name: onlyoffice-documentserver-claim3
            - mountPath: /usr/share/fonts
              name: onlyoffice-documentserver-claim4
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
  updateStrategy: {}
  volumeClaimTemplates:
    - metadata:     
        labels:
          io.kompose.service: onlyoffice-documentserver-claim0
        name: onlyoffice-documentserver-claim0
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
      status: {}
    - metadata:       
        labels:
          io.kompose.service: onlyoffice-documentserver-claim1
        name: onlyoffice-documentserver-claim1
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
      status: {}
    - metadata:        
        labels:
          io.kompose.service: onlyoffice-documentserver-claim2
        name: onlyoffice-documentserver-claim2
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
      status: {}
    - metadata:        
        labels:
          io.kompose.service: onlyoffice-documentserver-claim3
        name: onlyoffice-documentserver-claim3
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
      status: {}
    - metadata:        
        labels:
          io.kompose.service: onlyoffice-documentserver-claim4
        name: onlyoffice-documentserver-claim4
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
      status: {}