apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --controller replicationController --replicas 2 --controller statefulset
    kompose.version: 1.26.1 (a9d05d509)  
  labels:
    io.kompose.service: onlyoffice-rabbitmq
  name: onlyoffice-rabbitmq
spec:
  clusterIP: None
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
  selector:
    io.kompose.service: onlyoffice-rabbitmq
  type: ClusterIP
status:
  loadBalancer: {}
